---
title: "Agrupamiento"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(caret)
library(xgboost)
library(knitr)
```

```{r}
datos <- read.csv("../datos/datos_listos.csv")
datos <- datos %>% select(-X)
```

# Base de datos


Para el modlo de agrupamiento se escogerá la base de datos previamente depurada, a conrinuacion se crearan varaiables asociadas a cada uno de los barrios. de la siguiente base de datos se usaran algunas variables como pivotes para asociarlas a cada uno de los barios:


```{r}
str(datos)
```


## Creacion de variables 

```{r}
datos %>% group_by(BARRIO, GRAVEDAD) %>% summarise(n = n()) %>% spread(GRAVEDAD, value = n) %>%
  mutate(`Con heridos` =ifelse(is.na(`Con heridos`), 0, `Con heridos`),
         `Con muertos` =ifelse(is.na(`Con muertos`), 0, `Con muertos`),
         `Solo daños` =ifelse(is.na(`Solo daños`), 0, `Solo daños`)) -> datos_agrupamiento1


datos %>% group_by(BARRIO, CLASE_ACCIDENTE) %>% summarise(n = n()) %>% spread(CLASE_ACCIDENTE, value = n) %>%
  mutate( Atropello=ifelse(is.na(Atropello), 0, Atropello ),
          `Caída Ocupante`=ifelse(is.na(`Caída Ocupante`), 0,`Caída Ocupante` ),
           Choque =ifelse(is.na(Choque), 0,Choque ),
          Otro =ifelse(is.na(Otro), 0,Otro )) -> datos_agrupamiento2

datos %>% 
  mutate(DIA = ifelse(DIA %in%c("Sab", "Dom"), "FinSemana", "semana")) %>% 
  group_by(BARRIO, DIA) %>% summarise(n = n()) %>% 
    spread(DIA, value = n) %>% mutate(Semana = round((semana)/(FinSemana+semana),4)) %>%
  select(-semana, -FinSemana) %>% 
  mutate(Semana = ifelse(is.na(Semana), 0, Semana))->datos_agrupamiento3
  


datos_agrupamiento <- datos_agrupamiento1 %>% inner_join(datos_agrupamiento2) %>% inner_join(datos_agrupamiento3)
x_agrupamiento <- datos_agrupamiento %>% select(BARRIO)
datos_agrupamiento <- datos_agrupamiento [,-1]
```


## analisis exploraatorio 


```{r}
summary(datos_agrupamiento)
```


```{r}
library(psych)
pairs.panels(datos_agrupamiento[,-1], 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE # show correlation ellipses
             )
```

```{r}
datos_agrupamiento <- datos_agrupamiento
set.seed(3) 
centers <- 2:10
resultados <- vector(mode="list",length = 9)
for (i in 1:length(centers)){
  resultados[[i]] <- kmeans(x=datos_agrupamiento,centers=centers[i],nstart = 3)
}


```


```{r}
grupos <- do.call("rbind",lapply(resultados,"[[",1))
grupos <- as.data.frame(t(grupos))
names(grupos) <- paste0("K",2:10)
datos_ilustracion_cl <- data.frame(datos_agrupamiento, grupos)
```





```{r}
grph_iulstr_cl_k <- ggplot(datos_ilustracion_cl,aes(x=Caída.Ocupante,y=Con.muertos))
g1 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K2))) + theme_bw() + labs(title = "K=2",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g2 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K3))) + theme_bw() + labs(title = "K=3",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g3 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K4))) + theme_bw() + labs(title = "K=4",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g4 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K5))) + theme_bw() + labs(title = "K=5",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
gridExtra::grid.arrange(g1,g2,g3,g4)
```





```{r}
metrica_cl <- do.call("rbind",lapply(resultados,"[[",5))
num_centros <- 2:10
res_num_cen <- data.frame(num_centros,metrica_cl)
grph_metrica_cl <- ggplot(res_num_cen,aes(x=num_centros,xend=num_centros,y=0,yend=metrica_cl))
grph_metrica_cl + geom_point(aes(x=num_centros,y=metrica_cl)) +  geom_segment() + theme_bw() + labs(title = "Desempeño del agrupamiento \n en función de K",
                                      x = "K (cantidad de centros)",
                                      y = "Métrica de desempeño")
```





```{r}
grupo <- grupos$K4
cl_medias <- aggregate(.~grupo,data=datos_agrupamiento,FUN=mean)
cl_sd <- aggregate(.~grupo,data=datos_agrupamiento,FUN=sd)

(cl_medias)
```




```{r}
grph_bxp <- ggplot(datos_ilustracion_cl,aes(y=Semana,colour = factor(K4)))
grph_bxp + geom_boxplot(aes(group=factor(K4)),orientation="x") + theme_bw() + 
  labs(title = "Boxplot del score de buró para cada grupo",
                                      x = "",
                                      y = "Score de buró",colour="Grupo") + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())
```









```{r}
grupo <- grupos$K4
cl_medias <- aggregate(.~grupo,data=datos_agrupamiento,FUN=median)
cl_sd <- aggregate(.~grupo,data=datos_agrupamiento,FUN=sd)

(cl_medias)
```




```{r}
grupo <- grupos$K4
datos_agrupados <- datos_agrupamiento %>% mutate(BARRIO = x_agrupamiento$BARRIO, grupo)

```


# mapa 





```{r}
library(rgdal)
library(leaflet)

barrios_med <- readOGR("../Barrios de Medellín/Barrio_Vereda.shp",layer="Barrio_Vereda")
nombres_barrios <- iconv(barrios_med@data$NOMBRE,"UTF-8","ISO_8859-1")
barrios_mapa <- data.frame(BARRIO = nombres_barrios)
b <- datos_agrupados %>% left_join(barrios_mapa)


m=leaflet(barrios_med)
m=addTiles(m)
c <- barrios_med$CODIGO
m <- addPolygons(m,popup=nombres_barrios)
m <- addTiles(m)
colores <- sample(x=c("orange","green","yellow"),size=length(nombres_barrios),replace=TRUE)
m=addPolygons(m,popup=nombres_barrios,color=colores)
m

```































