---
title: "Entendimiento"
author: "NN"
date: "18/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
rm(list = ls())
library(readxl)
library(tidyverse)
library(lubridate)
library(caret)
library(fastDummies)
require(randomForest)
library(ridge)
library(ranger)
library(psych)
library(glmnet)
library(rpart)
require(randomForest)
```



```{r}
datos <- read.csv("../datos/datos_listos.csv")
datos %>% filter(CLASE_ACCIDENTE != "Incendio", BARRIO!="") -> datos 

```


```{r}

datos <- datos %>%select(CLASE_ACCIDENTE, GRAVEDAD_ACCIDENTE,
                          DISEÑO, COMUNA, BARRIO, LATITUD,
                          LONGITUD, FECHA_ACCIDENTES) %>%
  mutate(CLASE_ACCIDENTE = factor(CLASE_ACCIDENTE, 
                                  levels=c("Atropello",
                                           "Caída Ocupante", 
                                           "Choque", "Otro", "Volcamiento")))
```



```{r}
FECHA_ACCIDENTE <- dmy(substr(datos$FECHA_ACCIDENTES, 1,10))
x <- wday(FECHA_ACCIDENTE)
DIA <- ifelse(x == 1, "Dom",
              ifelse(x == 2, "Lun",
                     ifelse(x == 3, "Mar",
                            ifelse(x == 4, "Mie",
                                   ifelse(x == 5, "Jue",
                                          ifelse(x == 6, "Vie","Sab"))))))
MES <- month(FECHA_ACCIDENTE)
AÑO <- year(FECHA_ACCIDENTE)
hora <- hm(substr(datos$FECHA_ACCIDENTE, 12,16))
HORA  <- round(hour(hora)+minute(hora)/60, 3)
DIA_MES <- mday(FECHA_ACCIDENTE)
SEMANA <- week(FECHA_ACCIDENTE)
DIA_AÑO <- yday(FECHA_ACCIDENTE)
datos <- datos %>% mutate(FECHA_ACCIDENTE, AÑO, MES,DIA_MES,SEMANA, DIA,DIA_AÑO, HORA)
str(datos)
```


```{r}
FESTIVOS <- read.csv("../datos/FESTIVOS.csv")
FESTIVOS <-  FESTIVOS%>% mutate(FESTIVO = 1)
FESTIVOS$FECHA <- dmy(FESTIVOS$FECHA)

FERIAS  <- readxl::read_excel("../datos/Ferias.xlsx")
FERIAS<-  FERIAS%>% mutate(FERIA = 1)

FERIAS$FECHA <- ymd(FERIAS$FECHA)
str(FERIAS)
```




```{r}



clases <- c( "Atropello", "Caída Ocupante", "Choque", "Otro","Volcamiento" )

datos %>%
  select(FECHA_ACCIDENTE,CLASE_ACCIDENTE, GRAVEDAD_ACCIDENTE, DISEÑO,  AÑO, MES,DIA, SEMANA, DIA_MES, HORA) %>% 
  group_by(FECHA_ACCIDENTE, CLASE_ACCIDENTE,GRAVEDAD_ACCIDENTE, DISEÑO,AÑO,MES,DIA, SEMANA, DIA_MES) %>%
  summarise( CASOS = n()) %>%
  ungroup()  %>% 
   full_join(FERIAS,by = c("FECHA_ACCIDENTE" = "FECHA")) %>% 
   full_join(FESTIVOS,by = c("FECHA_ACCIDENTE" = "FECHA")) %>% 
  mutate(FERIA = ifelse(is.na(FERIA), 0, 1)) %>% 
  mutate(FESTIVO = ifelse(is.na(FESTIVO), 0, 1)) %>% 
  select(-FECHA_ACCIDENTE) %>%
  filter(CLASE_ACCIDENTE == clases[3]) %>%
  select(-CLASE_ACCIDENTE) -> datos_modelo
```

## Predicción

## diario ridge y lasso



```{r}

x <- model.matrix(CASOS ~ ., datos_modelo)[, -1]    
y <- datos_modelo$CASOS
train <- x[,"AÑO"] <2018
test <- x[,"AÑO"] >= 2018 &  x[,"AÑO"] < 2020
x_train <- x[train,]
x_test <- x[test,]
y_train <- y[train]
y_test <- y[test]

gridz <- 10^seq(-2, 5, length = 100)            
ridge_mod <- glmnet(x_train, y_train, alpha = 0, lambda = gridz)
lasso_mod <- glmnet(x_train, y_train, alpha = 1, lambda = gridz)

#par(mfrow = c(1,2))
#plot(ridge_mod, xvar = "lambda", label = TRUE, xlim = c(-5.5, 10), lwd = 2)   
#plot(lasso_mod, xvar = "lambda", label = TRUE, xlim = c(-5.5, 10), lwd = 2)   

cv_ridge<-cv.glmnet(x_train, y_train,alpha=0)
cv_lasso<-cv.glmnet(x_train, y_train,alpha=1)
best_lambda_ridge <- cv_ridge$lambda.min
best_lambda_lasso <- cv_lasso$lambda.min
out_ridge <- glmnet (x_train, y_train,alpha=0)
out_lasso <- glmnet (x_train, y_train, alpha=1)

coef_ridge <- predict(out_ridge, type = "coefficients", s = best_lambda_ridge)
coef_lasso <- predict(out_lasso, type = "coefficients", s = best_lambda_lasso)


ridge_pred_entreno <- predict(ridge_mod, s = best_lambda_ridge, newx = x_train)
lasso_pred_entreno <- predict(lasso_mod, s = best_lambda_lasso, newx = x_train)





ridge <- mean((ridge_pred_entreno - y_train)^2)
lasso <- mean((lasso_pred_entreno - y_train )^2)


ECM_entrno <- data.frame(ridge, lasso)

ridge_pred_prueba<- predict(ridge_mod, s = best_lambda_ridge, newx = x_test)
lasso_pred_prueba<- predict(lasso_mod, s = best_lambda_lasso, newx = x_test)

ridge <- mean((ridge_pred_prueba - y_test)^2)
lasso <- mean((lasso_pred_prueba - y_test)^2)

ECM_prueba <- data.frame(ridge, lasso)



ridge_pred_2020 <- predict(ridge_mod, s = best_lambda_ridge, newx = x[x[, "AÑO"]==2020,])
lasso_pred_2020 <- predict(lasso_mod, s = best_lambda_lasso, newx = x[x[, "AÑO"]==2020,])

ridge <- mean((ridge_pred_2020 -  y[x[, "AÑO"]==2020])^2)
lasso <- mean((lasso_pred_2020 -  y[x[, "AÑO"]==2020])^2)


ECM_2020 <- data.frame(ridge, lasso)


ECM <- rbind(ECM_entrno,ECM_prueba,ECM_2020)
ECM

```

## modelo poissson

```{r}

datos_modelo3 <-datos_modelo2 %>%  select(AÑO, DIA, CASOS)
datos_train <- datos_modelo3 %>% filter(AÑO <2018)
datos_test <- datos_modelo3 %>% filter(AÑO %in% c(2018,2020))





mod <- glm(CASOS ~ ., data = datos_train, family = poisson(link = "log"))
pt <- predict(mod, newdata = datos_train,type = "response")
mean((pt-datos_train$CASOS)^2)

pt <- predict(mod, newdata = datos_test,type = "response")
mean((pt-datos_test$CASOS)^2)
```


```{r}
suav <- HoltWinters(datos_train$CASOS,seasonal="additive")

```







## todos los casos diarios 


```{r}

```








```{r}
library(randomForest)

train <- x[,"AÑO"] <2018
test <- x[,"AÑO"] >= 2018 &  x[,"AÑO"] < 2020

entreno <- datos_modelo$AÑO < 2018
test <- datos_modelo$AÑO >= 2018 & datos_modelo$AÑO  < 2020


df_train <- datos_modelo[entreno, ]
df_test <- datos_modelo[test, ]
model <- randomForest(CASOS ~.,data = df_train)
mean((predict(model, df_test)-df_test$CASOS)^2)
mean((predict(model, df_train)-df_train$CASOS)^2)
```




```{r}

predit <-  lasso_pred[,1]
data.frame(x_test) %>% select(AÑO, MES, SEMANA, DIA_MES) %>% cbind(data.frame(y_test, predit))-> resul 

```

anual  

```{r}
resul %>% group_by(AÑO, MES) %>% summarise(casos = sum(y_test), casos_p = sum(predit)) %>% mutate(ECM = (casos-casos_p)^2)
```









###############################
