---
title: "Entendimiento"
author: "NN"
date: "18/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
rm(list = ls())
library(readxl)
library(tidyverse)
library(lubridate)
library(caret)
library(xgboost)
library(fastDummies)
library(glmnet)
library(rpart)
library(rpart.plot)
require(randomForest)
library(kableExtra)
library(ridge)
library(ranger)
library(psych)
```



```{r}
datos <- read.csv("../datos/datos_listos.csv", encoding = "latin1")
datos %>% filter(CLASE_ACCIDENTE != "Incendio", BARRIO!="") -> datos 

```





```{r}

datos <- datos %>%select(CLASE_ACCIDENTE, GRAVEDAD,
                          DISEÑO, COMUNA, BARRIO, LATITUD,
                          LONGITUD, FECHA_ACCIDENTES) %>%
  mutate(CLASE_ACCIDENTE = factor(CLASE_ACCIDENTE, 
                                  levels=c("Atropello",
                                           "Caída Ocupante", 
                                           "Choque", "Otro", "Volcamiento")))
```



```{r}
FECHA_ACCIDENTE <- ymd(substr(datos$FECHA_ACCIDENTES, 1,10))
x <- wday(FECHA_ACCIDENTE)
DIA <- ifelse(x == 1, "Dom",
              ifelse(x == 2, "Lun",
                     ifelse(x == 3, "Mar",
                            ifelse(x == 4, "Mie",
                                   ifelse(x == 5, "Jue",
                                          ifelse(x == 6, "Vie","Sab"))))))
MES <- month(FECHA_ACCIDENTE)
AÑO <- year(FECHA_ACCIDENTE)
hora <- hm(substr(datos$FECHA_ACCIDENTE, 12,16))
HORA  <- round(hour(hora)+minute(hora)/60, 3)
DIA_MES <- mday(FECHA_ACCIDENTE)
datos <- datos %>% mutate(FECHA_ACCIDENTE, AÑO, MES,DIA_MES, DIA)

SEMANA <- week(FECHA_ACCIDENTE)
DIA_AÑO <- yday(FECHA_ACCIDENTE)
datos <- datos %>% mutate(FECHA_ACCIDENTE, AÑO, MES,DIA_MES,SEMANA, DIA,DIA_AÑO, HORA)
str(datos)
```


```{r}
datos_modelo <- datos %>%
  select(FECHA_ACCIDENTE,CLASE_ACCIDENTE, GRAVEDAD, DISEÑO,  AÑO, MES, SEMANA, DIA_MES, HORA) %>% 
  group_by(FECHA_ACCIDENTE, CLASE_ACCIDENTE,GRAVEDAD, DISEÑO,AÑO,MES, SEMANA, DIA_MES) %>% summarise( n = n()) %>% ungroup() %>%  select(-FECHA_ACCIDENTE)
```


## Predicción

```{r}
datos_modelo  %>% filter(CLASE_ACCIDENTE == "Caída Ocupante") %>% select(-CLASE_ACCIDENTE)%>% 
  dummy_cols( select_columns = c('GRAVEDAD', "DISEÑO"),
           remove_selected_columns = TRUE)  ->datos_modelo

x <- model.matrix(n ~ ., datos_modelo)[, -1]    
y <- datos_modelo$n
train <- x[,"AÑO"] < 2019
x_train <- x[train,]
x_test <- x[!train,]
y_train <- y[train]
y_test <- y[!train]
```

```{r}
gridz <- 10^seq(-2, 5, length = 100)            
ridge_mod <- glmnet(x_train, y_train, alpha = 0, lambda = gridz)
lasso_mod <- glmnet(x_train, y_train, alpha = 1, lambda = gridz)

par(mfrow = c(1,2))
plot(ridge_mod, xvar = "lambda", label = TRUE, xlim = c(-5.5, 10), lwd = 2)   
plot(lasso_mod, xvar = "lambda", label = TRUE, xlim = c(-5.5, 10), lwd = 2)   
```


```{r}
cv_ridge<-cv.glmnet(x_train, y_train,alpha=0)
cv_lasso<-cv.glmnet(x_train, y_train,alpha=1)
best_lambda_ridge <- cv_ridge$lambda.min
best_lambda_lasso <- cv_lasso$lambda.min
```


```{r}
out_ridge <- glmnet (x_train, y_train,alpha=0)
out_lasso <- glmnet (x_train, y_train, alpha=1)

coef_ridge <- predict(out_ridge, type = "coefficients", s = best_lambda_ridge)
coef_lasso <- predict(out_lasso, type = "coefficients", s = best_lambda_lasso)

```

```{r}
ridge_pred <- predict(ridge_mod, s = best_lambda_ridge, newx = x_test)
lasso_pred <- predict(lasso_mod, s = best_lambda_lasso, newx = x_test)

ridge <- mean((ridge_pred - y_test)^2)
lasso <- mean((lasso_pred - y_test)^2)

d <- data.frame(ridge, lasso)
d %>% kable(caption = "ECM")
```




```{r}

predit <-  lasso_pred[,1]
data.frame(x_test) %>% select(AÑO, MES, SEMANA, DIA_MES) %>% cbind(data.frame(y_test, predit))-> resul 

```

anual  

```{r}
resul %>% group_by(AÑO) %>% summarise(casos = sum(y_test), casos_p = sum(predit)) %>% mutate(ECM = (casos-casos_p)^2)
```



```{r}
ridge_pred <- predict(ridge_mod, s = best_lambda_ridge, newx = x_train)
lasso_pred <- predict(lasso_mod, s = best_lambda_lasso, newx = x_train)

ridge <- mean((ridge_pred - y_train)^2)
lasso <- mean((lasso_pred - y_train )^2)

d <- data.frame(ridge, lasso)
d %>% kable(caption = "ECM")
```
```{r}
set.seed(101)

# hyperparameter grid search
hyper_grid_rf <- expand.grid(
  mtry       = seq(1, 3, by = 1),
  node_size  = seq(7, 30, by = 2),
  sampe_size = c(.55, .632, .70, .80),
  OOB_RMSE   = 0
)

for(i in 1:nrow(hyper_grid_rf)) {
  
  # train model
  model <- ranger(
    formula         = y_train ~ ., 
    data            = train, 
    num.trees       = 500,
    mtry            = hyper_grid_rf$mtry[i],
    min.node.size   = hyper_grid_rf$node_size[i],
    sample.fraction = hyper_grid_rf$sampe_size[i],
    seed            = 101
  )
  
  # add OOB error to grid
  hyper_grid_rf$OOB_RMSE[i] <- sqrt(model$prediction.error)
}

hyper_grid_rf %>% 
  dplyr::arrange(OOB_RMSE) %>%
  head(10)

```


###############################
# varibles para agrupamiento

```{r}
datos_agrupamiento1 <- datos %>% group_by(BARRIO, GRAVEDAD) %>%
  summarise(n = n()) %>% spread(GRAVEDAD, value = n) %>%
  mutate(`Con heridos` =ifelse(is.na(`Con heridos`), 0, `Con heridos`),
         `Con muertos` =ifelse(is.na(`Con muertos`), 0, `Con muertos`),
         `Solo daños` =ifelse(is.na(`Solo daños`), 0, `Solo daños`))


datos_agrupamiento2 <- datos %>% group_by(BARRIO, CLASE_ACCIDENTE) %>%
  summarise(n = n()) %>% spread(CLASE_ACCIDENTE, value = n) %>%
  mutate( Atropello=ifelse(is.na(Atropello), 0, Atropello ),
          `Caída Ocupante`=ifelse(is.na(`Caída Ocupante`), 0,`Caída Ocupante` ),
           Choque =ifelse(is.na(Choque), 0,Choque ),
          Otro =ifelse(is.na(Otro), 0,Otro ),
          Volcamiento =ifelse(is.na(Volcamiento), 0,Volcamiento ))

#datos %>% group_by(BARRIO, DIA) %>% summarise(n = n()) %>%
#  mutate(DIA = ifelse(DIA %in%c("Vie", "Sab", "Dom"), "FinSemana", "Semana"))
datos_agrupamiento2 <- datos_agrupamiento2[,-1]
datos_agrupamiento1 <- datos_agrupamiento1[,-1]
datos_agrupamiento <- data.frame(datos_agrupamiento1,datos_agrupamiento2)
```
```{r}
pairs.panels(datos_agrupamiento[,-1], 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE # show correlation ellipses
             )
```
```{r}
pca_nci  <- prcomp(datos_agrupamiento, scale = TRUE)
```


```{r}
datos_agrupamiento <- datos_agrupamiento
set.seed(3) 
centers <- 2:10
resultados <- vector(mode="list",length = 9)
for (i in 1:length(centers)){
  resultados[[i]] <- kmeans(x=datos_agrupamiento,centers=centers[i],nstart = 3)
}


```


```{r}
grupos <- do.call("rbind",lapply(resultados,"[[",1))
grupos <- as.data.frame(t(grupos))
names(grupos) <- paste0("K",2:10)
datos_ilustracion_cl <- data.frame(datos_agrupamiento, grupos)
```





```{}
grph_iulstr_cl_k <- ggplot(datos_ilustracion_cl,aes(x=Caída.Ocupante,y=Con.muertos))
g1 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K2))) + theme_bw() + labs(title = "K=2",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g2 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K3))) + theme_bw() + labs(title = "K=3",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g3 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K4))) + theme_bw() + labs(title = "K=4",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
g4 <- grph_iulstr_cl_k + geom_point(aes(colour = factor(K5))) + theme_bw() + labs(title = "K=5",
                                      x = "Con.heridos",
                                      y = "Solo.daños",colour="Grupo")
(g1 | g2)/
(g3 | g4)
```





```{r}
metrica_cl <- do.call("rbind",lapply(resultados,"[[",5))
num_centros <- 2:10
res_num_cen <- data.frame(num_centros,metrica_cl)
grph_metrica_cl <- ggplot(res_num_cen,aes(x=num_centros,xend=num_centros,y=0,yend=metrica_cl))
grph_metrica_cl + geom_point(aes(x=num_centros,y=metrica_cl)) +  geom_segment() + theme_bw() + labs(title = "Desempeño del agrupamiento \n en función de K",
                                      x = "K (cantidad de centros)",
                                      y = "Métrica de desempeño")
```





```{r}
grupo <- grupos$K4
cl_medias <- aggregate(.~grupo,data=datos_agrupamiento,FUN=mean)
cl_sd <- aggregate(.~grupo,data=datos_agrupamiento,FUN=sd)

(cl_medias)
```


```{r}
grph_bxp <- ggplot(datos_ilustracion_cl,aes(y=Solo.daños,colour = factor(K4)))
grph_bxp + geom_boxplot(aes(group=factor(K4)),orientation="x") + theme_bw() + 
  labs(title = "Boxplot del score de buró para cada grupo",
                                      x = "",
                                      y = "Score de buró",colour="Grupo") + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())
```



```{r}
datos %>% group_by(BARRIO, CLASE_ACCIDENTE) %>% summarise(n = n()) %>% spread(CLASE_ACCIDENTE, value = n) %>%
  mutate(`Con heridos` =ifelse(is.na(`Con heridos`), 0, `Con heridos`),
         `Con muertos` =ifelse(is.na(`Con muertos`), 0, `Con muertos`),
         `Solo daños` =ifelse(is.na(`Solo daños`), 0, `Solo daños`)) -> datos_agrupamiento
```



















